config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  resources :colaborators do
    member do
      get 'preview'
    end
    collection do
      get 'search'
    end
  end
  
  resources :colaborators

  # Defines the root path route ("/")
  root 'colaborators#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/colaborator.rb
class Colaborator < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_full_text,
                  against: {
                    email: 'A',
                    id: 'B'
                  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Cualquier controlador que herede de ApplicationController tendrá acceso a los métodos de Pagy::Backend
    include Pagy::Backend
end

app/controllers/colaborators_controller.rb
class ColaboratorsController < ApplicationController
  before_action :set_colaborator, only: %i[show edit update destroy]

  # GET /colaborators or /colaborators.json
  def index
    # @colaborators = Colaborator.all
    @pagy, @colaborators = pagy(Colaborator.all)

    return unless params[:query_text].present?

    @colaborators = @colaborators.search_full_text(params[:query_text])
  end

  # GET /colaborators/1 or /colaborators/1.json
  def show; end

  # GET /colaborators/new
  def new
    @colaborator = Colaborator.new
  end

  # GET /colaborators/1/edit
  def edit; end

  # POST /colaborators or /colaborators.json
  def create
    @colaborator = Colaborator.new(colaborator_params)

    respond_to do |format|
      if @colaborator.save
        format.html { redirect_to colaborator_url(@colaborator), notice: 'Colaborator was successfully created.' }
        format.json { render :show, status: :created, location: @colaborator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @colaborator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colaborators/1 or /colaborators/1.json
  def update
    respond_to do |format|
      if @colaborator.update(colaborator_params)
        format.html { redirect_to colaborator_url(@colaborator), notice: 'Colaborator was successfully updated.' }
        format.json { render :show, status: :ok, location: @colaborator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @colaborator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colaborators/1 or /colaborators/1.json
  def destroy
    @colaborator.destroy

    respond_to do |format|
      format.html { redirect_to colaborators_url, notice: 'Colaborator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Member action
  def preview; end

  # Collection action
  def search; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_colaborator
    @colaborator = Colaborator.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def colaborator_params
    params.require(:colaborator).permit(:name, :email, :direction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/colaborators_helper.rb
module ColaboratorsHelper
end

app/views/colaborators/_colaborator.html.erb
<div id="<%= dom_id colaborator %>">
  <p>
    <strong>ID:</strong>
    <%= colaborator.id %>
  </p>
  <p>
    <strong>Name:</strong>
    <%= colaborator.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= colaborator.email %>
  </p>

  <p>
    <strong>Direction:</strong>
    <%= colaborator.direction %>
  </p>

</div>

app/views/colaborators/_form.html.erb
<%= form_with(model: colaborator) do |form| %>
  <% if colaborator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(colaborator.errors.count, "error") %> prohibited this colaborator from being saved:</h2>

      <ul>
        <% colaborator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :direction, style: "display: block" %>
    <%= form.text_field :direction %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/colaborators/edit.html.erb
<h1>Editing colaborator</h1>

<%= render "form", colaborator: @colaborator %>

<br>

<div>
  <%= link_to "Show this colaborator", @colaborator %> |
  <%= link_to "Back to colaborators", colaborators_path %>
</div>

app/views/colaborators/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Colaborators</h1>
<hr>
<%= form_with url: colaborators_path, method: :get do |form|%>
  <%= 
  form.text_field :query_text, 
  placeholder: "Ingresa tu búsqueda", 
  value: params[:query_text]
  %>
<%end%>
<hr>
<div id="colaborators">
  <% @colaborators.each do |colaborator| %>
    <%= render colaborator %>
    <p>
      <%= link_to "Show this colaborator", colaborator %>
    </p>
  <% end %>
</div>
<p>
  <%= link_to "New colaborator", new_colaborator_path %>
</p>

<%== pagy_bootstrap_nav(@pagy) %>

app/views/colaborators/new.html.erb
<h1>New colaborator</h1>

<%= render "form", colaborator: @colaborator %>

<br>

<div>
  <%= link_to "Back to colaborators", colaborators_path %>
</div>

app/views/colaborators/preview.html.erb
<h1>Vista preview como ruta miembro</h1>

<h2>
Miembro de colección con ID: <%= params[:id] %>
</h2>

app/views/colaborators/search.html.erb
<h1>Buscador de colaboradores</h1>

app/views/colaborators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @colaborator %>

<div>
  <%= link_to "Edit this colaborator", edit_colaborator_path(@colaborator) %> |
  <%= link_to "Back to colaborators", colaborators_path %>

  <%= button_to "Destroy this colaborator", @colaborator, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColaboradoresRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# Bootstrap CDN%>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <body>
    <main class="container">
      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>